#!/bin/bash
if CCACHE_DISABLE=1 g++ test.c -o test.app --std=c++20 -lsqlite3 -Werror -Wfatal-errors; then
	# usleep 500000
	./test.app
else
	echo "Compilation failed. Unable to execute ./test.app."
fi